import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the folder layout under docs/. Ordering and
// labels come from each page's front matter and the _category_.json file in
// each folder.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
